version: '3'

volumes:
  pg_data:
  static:
  media:
  docs:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: mogubudu/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - docs:/app/api/docs/

  frontend:
    env_file: .env
    image: mogubudu/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: mogubudu/foodgram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/app/media
      - docs:/usr/share/nginx/html/api/docs/
    ports:
      - 8080:80